### ISSUE TITLE
Not registered for 0.1.1?

### ISSUE THREAD

**Issue by dasnixon** [ivanvotti/ember-pusher-component#2]
Can't find `0.1.1` when installing the `ember-cli-pusher` module (`ember install ember-cli-pusher`)

![screen shot 2015-05-18 at 2 04 59 pm](https://cloud.githubusercontent.com/assets/672057/7690214/fca20174-fd66-11e4-8f6c-bdab1b4bd907.png)

**Comment by dasnixon** [comment]
@ivanvotti believe you just need to create a release for `0.1.1`

**Comment by ivanvotti** [comment]
done:)
